path_pid:
  xy_deadzone: 0.08
  yaw_deadzone: 2
  odom_topic: /robot_coordinate
  LockupPoint:
    {
      x_max: 0.5, y_max: 0.5, yaw_max: 1
    }
  path1_pointX_pid: 
    {
      p: 0.85, i: 0.000, d: 0.15, out_max: 2, dead_zone: 0.005, I_Separate: 0.0,  I_Limit: 0.0, pre_feed: 0.5
    }

  path1_pointY_pid: 
    {
      p: 0.85, i: 0.000, d: 0.15, out_max: 2, dead_zone: 0.005, I_Separate: 0.0, I_Limit: 0.0, pre_feed: 0.5
    }

  path1_Yaw_pid: 
    {
      p: 0.013, i: 0.0, d: 0.0003, out_max: 1.0, dead_zone: 1, I_Separate: 500, I_Limit: 500, pre_feed: 0.0
    }
  